version: '2'
services:
  database:
    environment:
      - POSTGRES_USER=rest_test
      - POSTGRES_PASSWORD=rest_test
    build:
      context: .
      dockerfile: Database.Dockerfile
  app:
    environment:
      - DATABASE_URI=postgresql://rest_test:rest_test@database/rest_test
      - TEST_DATABASE_URI=postgresql://rest_test:rest_test@database/test_rest_test
      - FLASK_DEBUG=true
      - SECRET_KEY=some_secret
      - COVERALLS_REPO_TOKEN
    build:
      context: .
      dockerfile: App.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '80:5000'
    depends_on:
      - database
