version: '3.4'
services:
  database:
    environment:
      - POSTGRES_USER=http_quest
      - POSTGRES_PASSWORD=http_quest
    build:
      context: .
      dockerfile: DevDatabase.Dockerfile
    tmpfs: /pgtmpfs
    container_name: http_quest_database
    ports:
      - 5432:5432
  db_migrate_dev:
    environment:
      - DATABASE_URI=postgresql://http_quest:http_quest@http_quest_database/http_quest
      - APP_ENVIRONMENT=dev
    build:
      context: .
      dockerfile: Dockerfile
      target: db-migrate
    container_name: http_quest_db_migrate_dev
    depends_on:
      - database
  db_migrate_test:
    environment:
      - TEST_DATABASE_URI=postgresql://http_quest:http_quest@http_quest_database/http_quest_test
      - APP_ENVIRONMENT=test
    build:
      context: .
      dockerfile: Dockerfile
      target: db-migrate
    container_name: http_quest_db_migrate_test
    depends_on:
      - database
  app:
    environment:
      - APP_ENVIRONMENT=prod
      - APP_LOCALE=en
      - DATABASE_URI=postgresql://http_quest:http_quest@http_quest_database/http_quest
      - TEST_DATABASE_URI=postgresql://http_quest:http_quest@http_quest_database/http_quest_test
      - SECRET_KEY=some_secret
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '8000:80'
    container_name: http_quest_backend_app
    depends_on:
      - database
      - db_migrate_dev
  integration-tests:
    environment:
      - APP_ENVIRONMENT=test
      - TEST_DATABASE_URI=postgresql://http_quest:http_quest@http_quest_database/http_quest_test
    build:
      context: .
      dockerfile: Dockerfile
      target: db-migrate
    container_name: http_quest_integration_tests
    depends_on:
      - db_migrate_test
