version: '2'
services:
  database:
    environment:
      - POSTGRES_USER=rest_test
      - POSTGRES_PASSWORD=rest_test
    build:
      context: .
      dockerfile: Database.Dockerfile
  app:
    environment:
      - DATABASE_URL=postgresql://rest_test:rest_test@database/rest_test
    build:
      context: .
      dockerfile: App.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '80:5000'
    depends_on:
      - database
