version: '3.4'
services:
  database:
    environment:
      - POSTGRES_USER=http_quest
      - POSTGRES_PASSWORD=http_quest
    image: postgres:10
    tmpfs: /pgtmpfs
    container_name: http_quest_database
  build:
    environment:
      - APP_ENVIRONMENT=dev
      - APP_LOCALE=en
      - DATABASE_URI=postgresql://http_quest:http_quest@database/http_quest
      - TEST_DATABASE_URI=postgresql://http_quest:http_quest@database/http_quest_test
      - FLASK_DEBUG=true
      - SECRET_KEY=some_secret
      - COVERALLS_REPO_TOKEN
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '5000:5000'
    container_name: http_quest_backend_build
    depends_on:
      - database
  app:
    environment:
      - APP_ENVIRONMENT=prod
      - APP_LOCALE=en
      - DATABASE_URI=postgresql://http_quest:http_quest@database/http_quest
      - TEST_DATABASE_URI=postgresql://http_quest:http_quest@database/http_quest_test
      - SECRET_KEY=some_secret
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '8000:80'
    container_name: http_quest_backend_app
    depends_on:
      - database

