version: '3'
services:
  database:
    environment:
      - POSTGRES_USER=http_quiz
      - POSTGRES_PASSWORD=http_quiz
    build:
      context: .
      dockerfile: Database.Dockerfile
    tmpfs: /pgtmpfs
    container_name: http_quiz_database
  mailcatcher:
    image: "schickling/mailcatcher"
    ports:
      - '1080:1080'
      - '1025:1025'
    container_name: http_quiz_mailcatcher
  app:
    environment:
      - APP_ENVIRONMENT=dev
      - APP_LOCALE=hi
      - DATABASE_URI=postgresql://http_quiz:http_quiz@database/http_quiz
      - TEST_DATABASE_URI=postgresql://http_quiz:http_quiz@database/http_quiz_test
      - FLASK_DEBUG=true
      - HEADLESS=true
      - SECRET_KEY=some_secret
      - COVERALLS_REPO_TOKEN
    build:
      context: .
      dockerfile: App.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '80:5000'
    container_name: http_quiz_app
    depends_on:
      - database
      - mailcatcher
