version: '2'
services:
  database:
    environment:
      - POSTGRES_PASSWORD=root
    build:
      context: .
      dockerfile: Database.Dockerfile
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '80:5000'
    depends_on:
      - database
