"""change password column type

Revision ID: 59960b6283e6
Revises: ffc021d174b1
Create Date: 2018-05-20 13:25:12.065736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = '59960b6283e6'
down_revision = 'ffc021d174b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.batch_alter_table('user', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.batch_alter_table('user', sa.Column('password', sa.Binary(length=128), nullable=True))
    # ### end Alembic commands ###
