"""Add candidate table

Revision ID: 664b87341908
Revises: 9c0f1d800b4b
Create Date: 2018-05-13 11:48:54.749700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664b87341908'
down_revision = '9c0f1d800b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('token', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=64), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###
