"""Add new field quiz type

Revision ID: 7d3b6268f764
Revises: 664b87341908
Create Date: 2018-05-13 16:56:57.948290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3b6268f764'
down_revision = '664b87341908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('quiz_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'quiz_type')
    # ### end Alembic commands ###
