"""add a new column quiz_name

Revision ID: 9228ba1be97e
Revises: 59960b6283e6
Create Date: 2018-05-20 17:14:42.217005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9228ba1be97e'
down_revision = '59960b6283e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('quiz_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'quiz_name')
    # ### end Alembic commands ###
