"""Add password reset token column

Revision ID: 9c0f1d800b4b
Revises: a8f9df45ac5c
Create Date: 2018-05-06 15:44:59.442798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0f1d800b4b'
down_revision = 'a8f9df45ac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint('password_reset_token_unique_constraint', 'user', ['password_reset_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('password_reset_token_unique_constraint', 'user', type_='unique')
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
