"""create new table sequential quiz

Revision ID: ffc021d174b1
Revises: 7d3b6268f764
Create Date: 2018-05-15 17:04:30.005263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffc021d174b1'
down_revision = '7d3b6268f764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sequential_quiz',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=True),
        sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequential_quiz')
    # ### end Alembic commands ###
